spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cdc-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5432/debezium_master
    username: docker
    password: docker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
